---
title: "Exploratory Data Analysis Quiz 1"
author: "Francisco Martín"
date: "September, 2018"
output: html_document
---

## 1.-
Which of the following is a principle of analytic graphics?

- Only do what your tools allow you to do

- Integrate multiple modes of evidence   (Correct)

- Show box plots (univariate summaries)

- Don't plot more than two variables at at time

- Make judicious use of color in your scatterplots

Explanation -> Theory


## 2.-

What is the role of exploratory graphs in data analysis?


- The goal is for personal understanding.  (Correct)

- Axes, legends, and other details are clean and exactly detailed.

- They are used in place of formal modeling.

- Only a few are constructed.

Explanation -> Theory

## 3.-

Which of the following is true about the base plotting system?


- The system is most useful for conditioning plots

- Margins and spacings are adjusted automatically depending on the type of plot and the data

- Plots are typically created with a single function call

- Plots are created and annotated with separate functions   (Correct)

Explanation -> Theory

## 4.-

Which of the following is an example of a valid graphics device in R?


- A PNG file  (Correct)

- A Microsoft Word document

- The keyboard

- A file folder

- A socket connection


Explanation -> Theory

## 5.-

Which of the following is an example of a vector graphics device in R?


- GIF

- JPEG

- SVG  (Correct)

- PNG 

- TIFF

Explanation -> Theory

## 6.-

Bitmapped file formats can be most useful for

- Plots that are not scaled to a specific resolution

- Scatterplots with many many points  (Correct)

- Plots that require animation or interactivity

- Plots that may need to be resized

Explanation -> Theory

## 7.-

Which of the following functions is typically used to add elements to a plot in the base graphics system?


- boxplot()

- hist()

- plot()

- text()  (Correct)

Explanation -> Theory

## 8.-

Which function opens the screen graphics device for the Mac?


- pdf()

- quartz()  (Correct)

- png()

- bitmap()



Explanation -> Theory

## 9.-

What does the 'pch' option to par() control?


- the size of the plotting symbol in a scatterplot

- the plotting symbol/character in the base graphics system  (Correct)

- the line width in the base graphics system

- the orientation of the axis labels on the plot


Explanation -> Theory

## 10.-

If I want to save a plot to a PDF file, which of the following is a correct way of doing that?


- Open the PostScript device with postscript(), construct the plot, then close the device with dev.off().

- Construct the plot on the screen device and then copy it to a PDF file with dev.copy2pdf()  (Correct)

- Open the screen device with quartz(), construct the plot, and then close the device with dev.off().

- Construct the plot on the PNG device with png(), then copy it to a PDF with dev.copy2pdf().


Explanation -> Theory

